auth_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls'))
]

users/urls.py
from . import views
from django.urls import path

app_name = 'users'

urlpatterns = [
    path('profile/<slug:username>/', views.UserProfileView.as_view(), name='user_profile'),
    # path('alarms/'),
    # path('settings/'),
    # path('settings/privacy'),
    path('settings/', views.UserProfileSettingsView.as_view(), name='profile_settings'),
    path('friendlist/<slug:username>/', views.FriendlistView.as_view(), name='friendlist'),
    path('remove-friend/<slug:username>/', views.RemoveFriendView.as_view(), name='remove_friend'),
    path('accept-request-friend/', views.AcceptFriendView.as_view() , name='accept_request_friend'),
    path('reject-request-friend/', views.RejectFriendView.as_view(), name='reject_request_friend'),
    path('my-requested-friend/', views.GetMyRequestedFriendsView.as_view(), name='my_requested_friend'),
    path('add-friend/', views.AddFriendView.as_view(), name='add_friend'),
    path('login/', views.login_view, name='login'),
    path('register/', views.registration_view, name='register'),
    path('logout/', views.logout_view, name='logout')
    # капча + емейл?
]

users/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.core.validators import MaxValueValidator
from django.db import models
from django.conf import settings
from django.contrib.auth.base_user import BaseUserManager


class CustomUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('email должен быть указан')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)

        for field in ['username', 'first_name', 'last_name', 'age', 'gender', 'city']:
            if not extra_fields.get(field):
                raise ValueError(f'Поле {field} должно быть указано для обычных пользователей.')

        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Суперпользователь должен иметь is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Суперпользователь должен иметь is_staff=True.')

        # For superusers
        extra_fields.setdefault('username', 'admin')
        extra_fields.setdefault('first_name', '')
        extra_fields.setdefault('last_name', '')
        extra_fields.setdefault('age', None)
        extra_fields.setdefault('gender', '')
        extra_fields.setdefault('city', '')

        return self._create_user(email, password, **extra_fields)


# Модель пользователя
class CustomUser(AbstractBaseUser, PermissionsMixin):
    GENDERS = (("1", "Male"),
               ("2", "Female"))

    email = models.EmailField(max_length=64, unique=True, verbose_name='Электронная почта')
    username = models.CharField(max_length=48, unique=True, verbose_name='Имя пользователя')
    first_name = models.CharField(max_length=48, verbose_name='Имя')
    last_name = models.CharField(max_length=48, verbose_name='Фамилия')
    gender = models.CharField(choices=GENDERS, max_length=1, verbose_name='Гендер', blank=True, default='')
    age = models.PositiveIntegerField(validators=[MaxValueValidator(100)], verbose_name='Возраст', blank=True,
                                      null=True)
    city = models.CharField(max_length=48, verbose_name='Город')
    bio = models.TextField(max_length=1000, null=True, blank=True)
    data_joined = models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)  # ''' ПУТЬ ЗАГРУЗКИ '''
    is_active = models.BooleanField(default=True, verbose_name='Состояние аккаунта')
    is_staff = models.BooleanField(default=False, verbose_name='Статус персонала')  #

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def get_friends(self):
        friends = FriendShip.objects.filter(user=self, status='accepted').values_list('friend', flat=True)
        return CustomUser.objects.filter(id__in=friends)

    def add_friend(self, friend):
        """Отправляет запрос на добавление в друзья"""
        if self == friend:
            raise ValueError('Нельзя добавить в друзья самого себя')
        if FriendShip.objects.filter(user=self, friend=friend).exists():
            raise ValueError('Такой запрос в друзья уже существует')
        FriendShip.objects.create(user=self, friend=friend, status='requested')

    def remove_friend(self, friend):
        FriendShip.objects.filter(user=self, friend=friend).delete()
        FriendShip.objects.filter(user=friend, friend=self).delete()


class FriendShip(models.Model):
    STATUS_CHOICES = [
        ('requested', 'Requested'),
        ('accepted', 'Accepted'),
        ('rejected', 'Rejected')
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='friend_requests_sent', on_delete=models.CASCADE)
    friend = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='friend_requests_received',
                               on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='requested')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'friend')
        verbose_name = 'Дружба'
        verbose_name_plural = 'Дружба'

    def __str__(self):
        return f"{self.user} - {self.friend} ({self.status})"

class UserProfileSettings(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, unique=True, null=True, blank=True)
    invisible_friendlist = models.BooleanField(default=False, help_text='Закрытый список ваших друзей')

    class Meta:
        verbose_name = 'Настройки профиля'
        verbose_name_plural = 'Настройки профиля'

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from .models import CustomUser, FriendShip, UserProfileSettings

User = get_user_model()


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']


class UserRegistrForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Имя пользователя'
        self.fields['email'].label = 'Почта'
        self.fields['first_name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['gender'].label = 'Гендер'
        self.fields['age'].label = 'Возраст'
        self.fields['city'].label = 'Город'
        self.fields['bio'].label = 'Статус'

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'gender', 'age', 'city', 'bio']


class AddFriendForm(forms.Form):
    friend_id = forms.IntegerField(widget=forms.HiddenInput())

    def clean_friend_id(self):
        friend_id = self.cleaned_data['friend_id']
        if not User.objects.filter(id=friend_id).exists():
            raise forms.ValidationError('Такого пользователя не существует')
        return friend_id


class RejectFriendForm(forms.Form):
    request_id = forms.IntegerField(widget=forms.HiddenInput())

    def clean_request_id(self):
        request_id = self.cleaned_data['request_id']
        if not FriendShip.objects.filter(id=request_id).exists():
            raise forms.ValidationError('Такого пользователя не существует')
        return request_id


class AcceptFriendForm(forms.Form):
    request_id = forms.IntegerField(widget=forms.HiddenInput())

    def clean_request_id(self):
        request_id = self.cleaned_data['request_id']
        if not FriendShip.objects.filter(id=request_id).exists():
            raise forms.ValidationError('Такого пользователя не существует')
        return request_id


class UserProfileSettingsForm(forms.ModelForm):
    class Meta:
        model = UserProfileSettings
        fields = ['invisible_friendlist']
        labels = {'invisible_friendlist': 'Cписок друзей'}

users/views.py
import logging

from django.contrib.auth import login, authenticate, logout
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.edit import FormView, UpdateView
from django.contrib import messages
from .models import CustomUser, FriendShip, UserProfileSettings
from .forms import UserRegistrForm, UserLoginForm, AddFriendForm, RejectFriendForm, AcceptFriendForm, \
    UserProfileSettingsForm


logger = logging.getLogger('main')

def registration_view(request):
    if request.method == 'POST':
        form = UserRegistrForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # user.username = user.username.lower()
            user.save()
            messages.success(request, 'Вы успешно создали аккаунт')
            login(request, user)
            return redirect('/')
        else:
            return render(request, 'users/register.html', {'form': form})
    else:
        form = UserRegistrForm()
        return render(request, 'users/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Вы успешно вошли в аккаунт, {request.user.username}')
                return redirect('/')
        else:
            return render(request, 'users/login.html', {'form': form})
    else:
        form = UserLoginForm()
        return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    logout(request)
    messages.success(request, 'Вы успешно вышли из аккаунта')
    return redirect('/')


class UserProfileView(View):

    def get(self, request, *args, **kwargs):
        logger.info('go into UserProfileView')
        username_slug = kwargs.get('username')
        user = CustomUser.objects.get(username=username_slug)
        try:
            if user.username != request.user.username:
                privacy_settings = UserProfileSettings.objects.get(user=user)
                if privacy_settings.invisible_friendlist:
                    friend_list = user.get_friends()
                else:
                    friend_list = None
            else:
                friend_list = user.get_friends()
        except UserProfileSettings.DoesNotExist:
            friend_list = user.get_friends()
        if request.user.is_authenticated:
            is_friend = FriendShip.objects.filter(user=request.user, friend=user, status='accepted').exists() or \
                        FriendShip.objects.filter(user=user, friend=request.user, status='accepted').exists()
        else:
            is_friend = 'rejected'
        return render(request, 'users/user_profile.html',
                      context={'user': user, 'friend_list': friend_list, 'is_friend': is_friend})


class AddFriendView(LoginRequiredMixin, FormView):
    template_name = 'users/user_profile.html'
    form_class = AddFriendForm

    def form_valid(self, form):
        friend_id = form.cleaned_data['friend_id']
        friend = CustomUser.objects.get(id=friend_id)
        try:
            self.request.user.add_friend(friend)
            messages.success(self.request, 'Запрос на добавление в друзья успешно отправлен!')
        except ValueError as e:
            messages.error(self.request, str(e))
        return super().form_valid(form)

    def get_success_url(self):
        """
        Возвращает URL профиля добавленного друга.
        Используйте username друга для создания URL.
        """
        friend_id = self.request.POST.get('friend_id')
        friend = CustomUser.objects.get(id=friend_id)
        return reverse('users:user_profile', kwargs={'username': friend.username})


class RejectFriendView(LoginRequiredMixin, FormView):
    template_name = 'users/my_requested_friend.html'
    form_class = RejectFriendForm

    def form_valid(self, form):
        request_id = form.cleaned_data['request_id']
        friendship = FriendShip.objects.get(id=request_id)
        if friendship.friend == self.request.user:
            friendship.status = 'rejected'
            friendship.save()
            messages.success(self.request, "Запрос в друзья успешно отклонен")
        else:
            messages.error(self.request, "Вы не можете отклонить этот запрос")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('users:user_profile', kwargs={'username': self.request.user.username})


class AcceptFriendView(LoginRequiredMixin, FormView):
    template_name = 'users/my_requested_friend.html'
    form_class = AcceptFriendForm

    def form_valid(self, form):
        request_id = form.cleaned_data['request_id']
        with transaction.atomic():  # Используем атомарные транзакции для обеспечения целостности данных
            friendship = FriendShip.objects.get(id=request_id)
            if friendship.friend == self.request.user:
                # Обновляем существующую запись
                friendship.status = 'accepted'
                friendship.save()

                # Создаем зеркальную запись
                FriendShip.objects.create(
                    user=friendship.friend,  # Текущий пользователь, который принимает запрос
                    friend=friendship.user,  # Пользователь, отправивший запрос
                    status='accepted'  # Сразу устанавливаем статус как принятый
                )
                messages.success(self.request, "Вы успешно приняли запрос в друзья")
            else:
                messages.error(self.request, "Вы не можете принять этот запрос")
            return super().form_valid(form)

    def get_success_url(self):
        return reverse('users:user_profile', kwargs={'username': self.request.user.username})


class RemoveFriendView(LoginRequiredMixin, View):
    def post(self, request, username):
        user = request.user
        friend = get_object_or_404(CustomUser, username=username)
        if FriendShip.objects.filter(user=user, friend=friend, status='accepted').exists() or \
                FriendShip.objects.filter(user=friend, friend=user, status='accepted').exists():
            user.remove_friend(friend)
            messages.success(request, 'Друг успешно удален.')
        else:
            messages.error(request, 'Не удалось найти такого друга.')
        return redirect('users/user_profile', username=user.username)


class GetMyRequestedFriendsView(LoginRequiredMixin, ListView):
    template_name = 'users/my_requested_friend.html'  # friendlist
    model = CustomUser
    context_object_name = 'friend_requests'

    def get_queryset(self):
        return FriendShip.objects.filter(friend=self.request.user, status='requested')




class FriendlistView(ListView):
    template_name = 'users/frinedlist.html'
    model = CustomUser

    def get(self, request, *args, **kwargs):
        username_slug = kwargs.get('username')
        user = CustomUser.objects.get(username=username_slug)
        friend_list = user.get_friends()
        return render(request, 'users/friendlist.html', context={'friend_list': friend_list, 'user': user})


class UserProfileSettingsView(LoginRequiredMixin,UpdateView):
    template_name = 'users/user_profile_settings.html'
    model = UserProfileSettings
    form_class = UserProfileSettingsForm

    def get_success_url(self):
        return reverse('users:user_profile', kwargs={'username': self.request.user.username})

    def form_valid(self, form):
        messages.success(self.request, 'Настройки успешно обновлены!')
        return super().form_valid(form)

    def get_object(self):
        return UserProfileSettings.objects.get(user=self.request.user)

templates/users/friendlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3> Список друзей <a href="{% url 'users:user_profile' username=user.username %}">{{user.username}}</a></h3>


{% for friend in friend_list %}
    <p><a href="{% url 'users:user_profile' username=friend.username %}">{{ friend.username }}</a></p>
    {% if user.username == request.user.username %}
        <form action="{% url 'users:remove_friend' username=friend.username %}" method="post">
            {% csrf_token %}
            <button type="submit">Удалить из друзей</button>
        </form>
    {% endif %}
    {%empty%}
    <p>Пока тут пусто</p>
{% endfor %}

</body>
</html>

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

	<form method="POST" novalidate>
		{% csrf_token %}
		<h2>Авторизация</h2>

		{% for field in form %}
		<p>
			{% if field.errors %}
			<ul class="errorlist">
				{% for error in field.errors %}
				<li>{{ error }}</li>
				{% endfor %}
			</ul>
			{% endif %}
			{{ field.label_tag }} {{ field }}
		</p>
		{% endfor %}
		<input type="submit" value="Авторизация" />

		<p><a href="{% url 'users:register' %}">Зарегистрироваться</a></p>
	</form>
</body>
</html>

templates/users/my_requested_friend.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Новые заявки в друзья</h2>

{% for request in friend_requests %}
    <p><a href="{% url 'users:user_profile' username=request.user.username %}">{{ request.user.username }}</a>, отправил(а) запрос в друзья

        <form method="post" action="{% url 'users:accept_request_friend' %}">
            {% csrf_token %}
            <input type="hidden" name="request_id" value="{{ request.id }}">
            <button type="submit">Принять</button>
        </form>

        <form method="post" action="{% url 'users:reject_request_friend' %}">
            {% csrf_token %}
            <input type="hidden" name="request_id" value="{{ request.id }}">
            <button type="submit">Отклонить</button>
        </form>
    </p>
{% endfor %}

</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
	<form method="POST" novalidate>
		{% csrf_token %}
		<h2>Регистрация</h2>

		{% for field in form %}
		<p>
			{% if field.errors %}
			<ul class="errorlist">
				{% for error in field.errors %}
				<li>{{ error }}</li>
				{% endfor %}
			</ul>
			{% endif %}
			{{ field.label_tag }} {{ field }}
		</p>
		{% endfor %}
		<input type="submit" value="Зарегистрироваться" />
	</form>

</body>
</html>

templates/users/user_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user.username }}</title>
</head>
<body>

    {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="success">
                {{ message }}
            </div>
            {% endfor %}
        </div>
    {% endif %}

    {% if request.user.is_authenticated %}
        <p>Моя страница - <a href="{% url 'users:user_profile' username=request.user.username %}">{{ request.user.username }}</a>,
            <a href="{% url 'users:logout'%}">выйти</a></p>
        <a href="{% url 'users:profile_settings'%}">Настройки профиля</a>
    {% else %}
        <p><a href="{% url 'users:login' %}">Авторизоваться</a></p>
    {% endif %}

    <h2>Профиль</h2>
    <h3>{{ user.first_name}} {{user.last_name}}</h3>
    {% if request.user.is_authenticated %}
    {% if user.username != request.user.username %}
        {% if not is_friend %}
        <form method="post" action="{% url 'users:add_friend' %}">
            {% csrf_token %}
            <input type="hidden" name="friend_id" value="{{ user.id }}">
            <button type="submit">Добавить в друзья</button>
        </form>
        {% else %}

        <form action="{% url 'users:remove_friend' username=user.username %}" method="post">
            {% csrf_token %}
            <button type="submit">Удалить из друзей</button>
        </form>
        {%endif%}
    {% else %}
        {% if request.user.is_authenticated %}
            <p><a href="{% url 'users:my_requested_friend' %}">Заявки в друзья</a></p>
        {% endif %}
    {%endif%}
    {%endif%}

    <h4><a href="{% url 'users:friendlist' username=user.username %}">Список друзей</a></h4>
    {% for friend in friend_list|slice:":3" %}
        <p><a href="{% url 'users:user_profile' username=friend.username %}">{{ friend.username }}</a></p>

    {% endfor %}
</body>
</html>

templates/users/user_profile_settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Настройки</title>
</head>
<body>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить изменения</button>
</form>
</body>
</html>